# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{full-oauth2-server}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dorren Chen"]
  s.date = %q{2010-10-26}
  s.description = %q{fully implemented Oauth2 server}
  s.email = %q{dorrenchen@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "features/full-oauth2-server.feature",
     "features/step_definitions/full-oauth2-server_steps.rb",
     "features/support/env.rb",
     "lib/full-oauth2-server.rb",
     "spec/full-oauth2-server_spec.rb",
     "spec/spec_helper.rb",
     "test_client/.gitignore",
     "test_client/.rspec",
     "test_client/Gemfile",
     "test_client/README",
     "test_client/Rakefile",
     "test_client/app/controllers/application_controller.rb",
     "test_client/app/helpers/application_helper.rb",
     "test_client/app/views/layouts/application.html.erb",
     "test_client/autotest/discover.rb",
     "test_client/config.ru",
     "test_client/config/application.rb",
     "test_client/config/boot.rb",
     "test_client/config/environment.rb",
     "test_client/config/environments/development.rb",
     "test_client/config/environments/production.rb",
     "test_client/config/environments/test.rb",
     "test_client/config/initializers/backtrace_silencers.rb",
     "test_client/config/initializers/inflections.rb",
     "test_client/config/initializers/mime_types.rb",
     "test_client/config/initializers/secret_token.rb",
     "test_client/config/initializers/session_store.rb",
     "test_client/config/locales/en.yml",
     "test_client/config/routes.rb",
     "test_client/db/seeds.rb",
     "test_client/doc/README_FOR_APP",
     "test_client/lib/tasks/.gitkeep",
     "test_client/public/404.html",
     "test_client/public/422.html",
     "test_client/public/500.html",
     "test_client/public/favicon.ico",
     "test_client/public/images/rails.png",
     "test_client/public/index.html",
     "test_client/public/javascripts/application.js",
     "test_client/public/javascripts/controls.js",
     "test_client/public/javascripts/dragdrop.js",
     "test_client/public/javascripts/effects.js",
     "test_client/public/javascripts/prototype.js",
     "test_client/public/javascripts/rails.js",
     "test_client/public/robots.txt",
     "test_client/public/stylesheets/.gitkeep",
     "test_client/script/rails",
     "test_client/spec/spec_helper.rb",
     "test_client/test/performance/browsing_test.rb",
     "test_client/test/test_helper.rb",
     "test_client/vendor/plugins/.gitkeep",
     "test_provider/.gitignore",
     "test_provider/Gemfile",
     "test_provider/README",
     "test_provider/Rakefile",
     "test_provider/app/controllers/application_controller.rb",
     "test_provider/app/helpers/application_helper.rb",
     "test_provider/app/views/layouts/application.html.erb",
     "test_provider/config.ru",
     "test_provider/config/application.rb",
     "test_provider/config/boot.rb",
     "test_provider/config/database.yml",
     "test_provider/config/environment.rb",
     "test_provider/config/environments/development.rb",
     "test_provider/config/environments/production.rb",
     "test_provider/config/environments/test.rb",
     "test_provider/config/initializers/backtrace_silencers.rb",
     "test_provider/config/initializers/inflections.rb",
     "test_provider/config/initializers/mime_types.rb",
     "test_provider/config/initializers/secret_token.rb",
     "test_provider/config/initializers/session_store.rb",
     "test_provider/config/locales/en.yml",
     "test_provider/config/routes.rb",
     "test_provider/db/seeds.rb",
     "test_provider/doc/README_FOR_APP",
     "test_provider/lib/tasks/.gitkeep",
     "test_provider/public/404.html",
     "test_provider/public/422.html",
     "test_provider/public/500.html",
     "test_provider/public/favicon.ico",
     "test_provider/public/images/rails.png",
     "test_provider/public/index.html",
     "test_provider/public/javascripts/application.js",
     "test_provider/public/javascripts/controls.js",
     "test_provider/public/javascripts/dragdrop.js",
     "test_provider/public/javascripts/effects.js",
     "test_provider/public/javascripts/prototype.js",
     "test_provider/public/javascripts/rails.js",
     "test_provider/public/robots.txt",
     "test_provider/public/stylesheets/.gitkeep",
     "test_provider/script/rails",
     "test_provider/test/performance/browsing_test.rb",
     "test_provider/test/test_helper.rb",
     "test_provider/vendor/plugins/.gitkeep"
  ]
  s.homepage = %q{http://github.com/dorren/full-oauth2-server}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{fully implemented Oauth2 server}
  s.test_files = [
    "spec/full-oauth2-server_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<rack-oauth2>, [">= 0.2.1"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rack-oauth2>, [">= 0.2.1"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rack-oauth2>, [">= 0.2.1"])
  end
end

